### ISSUE TITLE
Eslint failing with error `No "exports" main defined in ./node_modules/eslint-config-sheriff/package.json`

### ISSUE THREAD

**Issue by sangrepura** [AndreaPontrandolfo/sheriff#268] opened 2024-09-28 00:21 UTC
```
[Error - 7:18:00 PM] Calculating config file for file:///package.json) failed.
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ./node_modules/eslint-config-sheriff/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:594:13)
    at resolveExports (node:internal/modules/cjs/loader:599:36)
    at Module._findPath (node:internal/modules/cjs/loader:676:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1138:27)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at _resolve (./node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:241814)
    at jiti (./node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:244531)
    at ./eslint.config.ts:1:213
    at evalModule (./node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313
 ```
 
 I'm using:
 
 ```
import sheriff from 'eslint-config-sheriff';
import { defineFlatConfig } from 'eslint-define-config';
import type { SheriffSettings } from '@sherifforg/types';

const sheriffOptions: SheriffSettings = {
  "react": true,
  "lodash": false,
  "remeda": false,
  "next": true,
  "astro": false,
  "playwright": false,
  "jest": false,
  "vitest": false
};

export default defineFlatConfig([...sheriff(sheriffOptions)])
```

Also:
```
 WARN  deprecated @sherifforg/types@4.1.1: the types are now exported directly from eslint-config-sheriff
 WARN  2 deprecated subdependencies found: glob@7.1.7, inflight@1.0.6
 ```
 
 Do the docs need to be updated?

**Comment by sangrepura** [comment] 2024-09-28 11:11
OK I fixed it by adding the following to my `.vscode/settings.json`:
```
"eslint.options": {
	"flags": ["unstable_ts_config"]
}
```

per [ESlint's documentation](https://eslint.org/docs/latest/use/configure/configuration-files#typescript-configuration-files)

Maybe add this to [the docs](https://www.eslint-config-sheriff.dev/docs/vscode-support) to reduce some friction for new folks?

**Comment by lishaduck** [comment] 2024-10-01 00:18
a) that docs PR looks good @AndreaPontrandolfo 
b) clearly something has gone dreadfully wrong with #233 (it should never need that, it's optional)

**Comment by lishaduck** [comment] 2024-11-01 15:11
@sangrepura, can you share what versions you're using?

**Comment by lishaduck** [comment] 2024-11-12 23:35
Duplicate of #201?

**Comment by AndreaPontrandolfo** [comment] 2024-11-12 23:39
@lishaduck Im doing a PR that will resolve both.

**Closed** 2024-11-13 00:23 UTC
Labels: enhancement, accepted
